###
POST http://127.0.0.1:3000/account
Content-Type: application/json

{
  "email": "",
  "password": ""
}
###
GET http://127.0.0.1:3000/account/
Content-Type: application/json
Authorization: Bearer 
###
POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
  "email": "",
  "password": ""
}
###
GET http://127.0.0.1:3000/auth/check
Content-Type: application/json
Authorization: Bearer 
###
POST http:// 127.0.0.1:3000/auth/refresh
Content-Type: application/json

{
  "token": ""
}
###
POST http://127.0.0.1:3000/auth/logout
Content-Type: application/json
Authorization: Bearer 

{
  "token": ""
}
###
PUT http://127.0.0.1:3000/account/uuid
Content-Type: application/json
Authorization: Bearer 

{
  "email": null,
  "password": null
}
###